# Generated by Django 6.0.5 on 2026-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_delivery_db',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=100)),
                ('orderdate', models.DateField()),
                ('itemname', models.CharField(max_length=100)),
                ('orderqty', models.IntegerField()),
                ('unitprice', models.FloatField()),
                ('totalamount', models.FloatField()),
                ('deliveryaddress', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'food_delivery_db',
            },
        ),
    ]
